export const path = {
  home: '/',
  login: '/login',
  register: '/register',
  hotel: '/hotel',
  hotelId: '/hotel/:id',
  flight: '/flight',
  flightId: '/flight/:id',
  tour: '/tour',
  tourDetailView: '/tour/detail-view',
  tourId: '/tour/:id',
  admin: '/admin',
  forgot_password: '/forgot-password',
  reset_password: '/reset-password',
  profile: '/profile',
  flight_detail:'/flight-detail',
  all_flight: '/flight/all-flight',
  home_stay: '/hotel/home-stay',
  hotel_detail:'/hotel/home-stay/hotel-detail',
} as const
