export { default as Banner } from './banner/banner'
export { default as BannerTour } from './banner/banner-tour'
export { default as Footer } from './footer/footer'
export { default as Header } from './header/header'
export { default as Perfect } from './perfect/perfect'
export { default as Review } from './review/review'
export {default as SearchTour } from './tour/search-tour/search-tour'
export {default as IntoTour } from './tour/into-tour/into-tour'
export {default as LocationTour } from './tour/location-tour/location-tour'
export { default as ThemeToogle } from './theme/theme-toogle'
export { default as RecentSearch } from './hotel/recent-search/recent-search'
export { default as FallIntroTravel } from './hotel/fall-intro-travel/fall-intro-travel'
