export { default as IconBed } from './IconBed'
export { default as IconFlight } from './IconFlight'
export { default as IconGoogle } from './IconGoogle'
export { default as IconHamberger } from './IconHamberger'
export { default as IconHotel } from './IconHotel'
export { default as IconNonEye } from './IconNonEye'
export { default as IconPlane } from './IconPlane'
export { default as IconEye } from './IocnEye'
export { default as IconVector} from './IconVector'
export { default as IconVectorDown} from './IconVectorDown'
export {default as IconVectorFlight} from "./IconVectorFlight"

export { default as IconAdd } from './IconAdd'
export { default as IconPlaces } from './IconPlaces'
export { default as IconCheckin } from './IconCheckin'
export { default as IconCheckout } from './IconCheckout'
export { default as IconTour } from './IconTour'
export { default as IconRoom } from './IconRoom'
export { default as IconSreach } from './IconSreach'

